### ISSUE TITLE
change banner background image

### ISSUE THREAD

**Issue by brandon1407** [BitsKing/bitsking.github.io#1]
We need to change the background image of the banner. Unfortunately it is acting very strange and wont change.

**Comment by jackmakesthings** [comment]
I'd like to help but I'm not sure what the problem is. What have you tried so far? The background image urls are set in the css; have you tried changing them there?

**Comment by brandon1407** [comment]
I'm fine now, I got it to work. I just had to put my background in an online storage platform like mediafire then link it in CSS. I don't know what was wrong before though.
